#ifndef GAMEDEF_H
#define GAMEDEF_H

#define TILE_WIDTH 100
#define GUTTER_WIDTH 15
#define CONTAINER_WIDTH (TILE_WIDTH * 4 + GUTTER_WIDTH * 5)

#define TILE_PADDING 12
#define TILE_VALUE_SIZE 12
#define TILE_VALUE_MARGIN 3

#define TILE_TEXT_MAX_SIZE 48

#endif // GAMEDEF_H
